name: jarvis
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  geolocator: ^11.0.0

  permission_handler: ^11.3.1

  flutter_dotenv: ^5.1.0 #for .env file

  cloud_firestore: ^4.14.0
  fake_cloud_firestore: ^2.4.8

  # For storing the profile data
  shared_preferences: ^2.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_ui_auth: ^1.13.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.0
  provider: ^6.1.2

  speech_to_text: ^6.6.0 #for speech to text

  http: ^1.2.0
  flutter_secure_storage: ^9.0.0 # Optional, for storing access tokens securely
  logging: ^1.0.0
  path_provider: ^2.0.9
  localstore: ^1.3.5 
  plugin_platform_interface: ^2.1.8
  flutter_gpt_tokenizer: ^0.1.1
  firebase_ui_shared: ^1.4.1

  flutter_tts: ^4.0.1
  volume_controller: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  google_sign_in_mocks: ^0.3.0
  firebase_auth_mocks: ^0.13.0
  mocktail: ^1.0.3
  test: ^1.16.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  logging: ^1.0.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  assets:
    - assets/Icon-192 copy.png
    - assets/dash.png
    - .env
    - assets/data/uncategorized_emails_10.json
    - assets/appLogo.png
    - assets/appLogoTransparent.png
